springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
spring:
  application:
    kakao-client-id: ${KAKAO_CLIENT_ID}
    kakao-redirect-uri: ${KAKAO_REDIRECT_URL}
  data:
    mongodb:
      host: ${HOST:localhost}
      port: ${PORT:27017}
      database: ${DATABASE}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASS}
  jwt:
    token:
      access-expiration-time: 43200000
      refresh-expiration-time: 604800000
jwt:
  access_secret: ${JWT_ACCESS_SECRET}
  refresh_secret: ${JWT_REFRESH_SECRET}

is-using-refresh-token: true