springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
spring:
  application:
    kakao-client-id: ${KAKAO_CLIENT_ID}
    kakao-redirect-uri: ${KAKAO_REDIRECT_URL}
  data:
    mongodb:
      host: ${HOST:localhost}
      port: ${PORT:27017}
      database: ${DATABASE:crayon}
      username: ${USERNAME}
      password: ${PASSWORD}
      authentication-database: admin
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS}
  jwt:
    token:
      access-expiration-time: 43200000
      refresh-expiration-time: 604800000
jwt:
  access_secret: ${JWT_ACCESS_SECRET}
  refresh_secret: ${JWT_REFRESH_SECRET}

is-using-refresh-token: true
image:
  path:
    ${IMAGE_PATH: /Users/yangts/Documents/crayon_img/}
#/home/ubuntu/images/