springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
spring:
  application:
    kakao-client-id: ${KAKAO_CLIENT_ID}
    kakao-redirect-uri: ${KAKAO_REDIRECT_URL}
  data:
    mongodb:
      uri: mongodb://${USERNAME}:${PASSWORD}@${HOST:localhost}:${PORT:27017}/${DATABASE:crayon}
      host: ${HOST:localhost}
      port: ${PORT:27017}
      database: ${DATABASE:crayon}
      username: ${USERNAME}
      password: ${PASSWORD}
      authentication-database: admin
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS}
  jwt:
    token:
      access-expiration-time: 922337203685477599
      refresh-expiration-time: 604800000
jwt:
  access_secret: ${JWT_ACCESS_SECRET}
  refresh_secret: ${JWT_REFRESH_SECRET}

is-using-refresh-token: true

lambda:
  uri: ${LAMBDA_URI}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

application:
  bucket:
    name: crayon-image-bucket

kakao:
  token_uri: ${KAKAO_TOKEN_URI}
  redirect_uri: ${KAKAO_REDIRECT_URI}
  grant_type: ${KAKAO_GRANT_TYPE}
  client_id: ${KAKAO_CLIENT_ID}
  user_info_uri: ${KAKAO_USER_INFO_URI}
