spring:
  profiles:
    active: local

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  use-fqn: true
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

lambda:
  uri: ${LAMBDA_URI}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

application:
  bucket:
    name: crayon-image

kakao:
  token_uri: ${KAKAO_TOKEN_URI}
  redirect_uri: ${KAKAO_REDIRECT_URI}
  grant_type: ${KAKAO_GRANT_TYPE}
  client_id: ${KAKAO_CLIENT_ID}
  user_info_uri: ${KAKAO_USER_INFO_URI}
