springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
spring:
  application:
    kakao-client-id: 4a62bf0f868170d27078e92ed07f6ccf
    kakao-redirect-uri: http://localhost:3000/kakao
  data:
    mongodb:
      host: 13.209.29.51
      port: 27017
      database: crayon
      username: root
      password: tkdskawk
      authentication-database: admin
    redis:
      host: localhost
      port: 6379
      password:
  jwt:
    token:
      access-expiration-time: 43200000
      refresh-expiration-time: 604800000
jwt:
  access_secret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345
  refresh_secret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345

is-using-refresh-token: true


image:
  path: /Users/jeongjunhui/Documents/crayon_img
#/home/ubuntu/images/