springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true

spring:
  data:
    mongodb:
      host: ${HOST:localhost}
      port: ${PORT:27017}
      database: ${DATABASE}
    redis:
      host: localhost
      port: 6379
  jwt:
    token:
      access-expiration-time: 43200000
      refresh-expiration-time: 604800000

jwt:
  access_secret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345
  refresh_secret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345

is-using-refresh-token: true