
name: Crayon-BE CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradle caching
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # gradle 빌드
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # 도커 이미지 생성 후 이미지 push
      - name: Docker build & push to dev
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/crayon .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/crayon

      # EC2 ssh 연결 후 이미지 pull
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_PASSWORD }}
          envs: GITHUB_SHA
          script: |
            EXISTING_CONTAINER_ID=$(sudo docker ps -q -f "publish=8080" -f "status=running")
            if [ ! -z "$EXISTING_CONTAINER_ID" ]; then
              sudo docker stop $EXISTING_CONTAINER_ID
              sudo docker rm $EXISTING_CONTAINER_ID
            fi

            EXISTING_CONTAINER_ID=$(sudo docker ps -q -f "publish=8080" -f "status=exited")
            if [ ! -z "$EXISTING_CONTAINER_ID" ]; then
              sudo docker rm $EXISTING_CONTAINER_ID
            fi

            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/crayon
            
            echo "USERNAME=${{ secrets.USERNAME }}" >> crayon.env
            echo "PASSWORD=${{ secrets.PASSWORD }}" >> crayon.env
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> crayon.env
            echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> crayon.env
            echo "JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}" >> crayon.env
            echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> crayon.env
            echo "LAMBDA_URI=${{ secrets.LAMBDA_URI }}" >> crayon.env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> crayon.env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> crayon.env
            echo "KAKAO_TOKEN_URI=${{ secrets.KAKAO_TOKEN_URI }}" >> crayon.env
            echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> crayon.env
            echo "KAKAO_GRANT_TYPE=${{ secrets.KAKAO_GRANT_TYPE }}" >> crayon.env
            echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> crayon.env
            echo "KAKAO_USER_INFO_URI=${{ secrets.KAKAO_USER_INFO_URI }}" >> crayon.env
            
            sudo docker run --name spring -d -p 8080:8080 --env-file ./crayon.env ${{ secrets.DOCKERHUB_USERNAME }}/crayon
            sudo docker image prune -a -f
